### ISSUE TITLE
이미지 한개만 예측할수도있는건가요???

### ISSUE THREAD

**Issue by bonseong11** [dslisleedh/PLKSR#5]
제 데이터셋으로 우선 학습시킨 pth모델이 생겼는데 test를 햇을땐 hr lr이 다있어야 하더라구요!! 혹시 한개의 이미지나 여러개의 이미지 hr이 없는 이 이미지 같은경우에는 예측이 혹시 가능한가요???

**Comment by dslisleedh** [comment]
안녕하세요, 이메일 주신 내용 확인했습니다.

말씀주신 방법으로 에측하려면 BasicSR의 SingleImageDataset[[Link]](https://github.com/XPixelGroup/BasicSR/blob/master/basicsr/data/single_image_dataset.py)를 사용하시거나,
```yaml
datasets:
  test_1:  # the 1st test dataset
    name: Set5
    type: SingleImageDataset
    dataroot_lq: .../datasets/Set5/LR_bicubic/X2
    filename_tmpl: '{}x2'
    io_backend:
      type: disk
```
BasicSR의 repository에 제공된 inference 코드[[Link]](https://github.com/XPixelGroup/BasicSR/blob/master/inference/inference_esrgan.py)를 수정하셔서 사용하시면 될 것 같습니다.

감사합니다.
